/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "inc.h"
/* Header for class com_hf_nativeimagemerge_ImageCompare */

#ifndef _Included_com_hf_nativeimagemerge_ImageCompare
#define _Included_com_hf_nativeimagemerge_ImageCompare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hf_nativeimagemerge_ImageCompare
 * Method:    nativeMerge
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageCompare_nativeMerge
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_hf_nativeimagemerge_ImageCompare
 * Method:    nativeTrim
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_hf_nativeimagemerge_ImageCompare_nativeTrim
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     com_hf_nativeimagemerge_ImageCompare
 * Method:    nativeXor
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageCompare_nativeXor
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_hf_nativeimagemerge_ImageCompare
 * Method:    nativeGenerateMask
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageCompare_nativeGenerateMask
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_hf_nativeimagemerge_ImageCompare
 * Method:    nativeGenerateFeatures
 * Signature: (J)[Lcom/hf/nativeimagemerge/ImageCompare/Feature;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hf_nativeimagemerge_ImageCompare_nativeGenerateFeatures
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hf_nativeimagemerge_ImageCompare
 * Method:    nativeCompareFeatures
 * Signature: (J[Lcom/hf/nativeimagemerge/ImageCompare/Feature;J[Lcom/hf/nativeimagemerge/ImageCompare/Feature;)I
 */
JNIEXPORT jint JNICALL Java_com_hf_nativeimagemerge_ImageCompare_nativeCompareFeatures
  (JNIEnv *, jclass, jlong, jlong, jobjectArray, jlong, jlong, jobjectArray);

/*
 * Class:     com_hf_nativeimagemerge_ImageCompare
 * Method:    nativeMergeBitmap
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageCompare_nativeMergeBitmap
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
