/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "inc.h"
/* Header for class com_hf_nativeimagemerge_ImageCompare */

#ifndef _Included_com_hf_nativeimagemerge_ImageCompare
#define _Included_com_hf_nativeimagemerge_ImageCompare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeCompareByFeature
 * Signature: (JJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeCompareByFeature
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeCompareByHash
 * Signature: (JJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeCompareByHash
        (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeMerge
 * Signature: (JJIII)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeMerge
        (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeMerge2
 * Signature: (JIIJII)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeMerge2
        (JNIEnv *, jclass, jlong, jint, jint, jlong, jint, jint);

/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeClip
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeClip
        (JNIEnv *, jclass, jlong, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
