/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "inc.h"
/* Header for class com_hf_nativeimagemerge_ImageCompare */

#ifndef _Included_com_hf_nativeimagemerge_ImageCompare
#define _Included_com_hf_nativeimagemerge_ImageCompare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeCompareByFeature
 * Signature: (JJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeCompareByFeature
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeCompareByHash
 * Signature: (JJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeCompareByHash
        (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeMerge
 * Signature: (JJIII)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeMerge
        (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeClipTop
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeClipTop
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_hf_nativeimagemerge_ImageMerge
 * Method:    nativeClipBottom
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_hf_nativeimagemerge_ImageMerge_nativeClipBottom
        (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
